# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_hGy-xu-su3vWeiBW2g_d4s32nnL-JY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import openai
import os

df=pd.read_csv('train.csv')
df

df_test=pd.read_csv('test.csv')
df_test

df.isnull().sum()

df_test.isnull().sum()

"""**DATA CLEANING (BOTH TRAIN AND TEST)**

"""

# fill the null values with 'Unknown'
df['Cabin']=df['Cabin'].fillna('Unknown')
df

df_test['Cabin']=df_test['Cabin'].fillna('Unknown')
df_test

df['Age'].median()

df_test['Age'].median()

df.isnull().sum()

df['Age'] = df['Age'].fillna(df['Age'].median())
df

df_test['Age'] = df_test['Age'].fillna(df_test['Age'].median())
df_test

df_test['Age'].median()

df_test.duplicated().sum() #no duplicates

"""**FEATURE ENGINEERING**

"""

#Deriving the feature
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

df_test["FamilySize"] = df_test["SibSp"] + df_test["Parch"] + 1

#categoriZe the ages
bins=[0,12,18,65,100]
labels=['Children','Teens','Adults','Seniors']
df['AgeGroup']=pd.cut(df['Age'],bins=bins,labels=labels,include_lowest=True)
df['AgeGroup'] = df['AgeGroup'].astype('category')

#Categorize For test data
bins=[0,12,18,65,100]
labels=['Children','Teens','Adults','Seniors']
df_test['AgeGroup']=pd.cut(df_test['Age'],bins=bins,labels=labels,include_lowest=True)
df_test['AgeGroup'] = df_test['AgeGroup'].astype('category')

df["TicketFreq"] = df.groupby("Ticket")["Ticket"].transform("count")

df_test["TicketFreq"] = df_test.groupby("Ticket")["Ticket"].transform("count")

df["Class"] = pd.qcut(df["Fare"], 3, labels=["Low", "Middle", "High"])
df

"""**DATA AGGREGATION/SUMMARIZATION**

"""

df['Age'].mean()

df['Age'].median()

df['Age'].std()

df['Fare'].mean()

df['Fare'].median()

df['Fare'].std()

survival_proportions = df['Survived'].value_counts(normalize=True)
survival_percentage = survival_proportions[1] * 100
non_survival_percentage = survival_proportions[0] * 100

print(f"Overall Survival Percentage: {survival_percentage:.2f}%")
print(f"Overall Non-Survival Percentage: {non_survival_percentage:.2f}%")

df.corr(numeric_only=True)

df.groupby("Sex")["Survived"].mean() * 100

df.groupby("Pclass")["Survived"].mean() * 100

df.groupby("AgeGroup",observed=True)["Survived"].mean() * 100

survived_by_gender=df.groupby("Sex",observed=True)["Survived"].mean() * 100
survived_by_gender

df["Survived"].corr(df["Fare"])
#weak positive correlation

df["Survived"].corr(df["Pclass"])

df["FamilySize"].corr(df["TicketFreq"])

"""**DATA VISUALIZATION**

"""

plt.hist(df['Age'], bins=20, color='red')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution')
plt.show()

plt.hist(df['Fare'], bins=20, color='blue')
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.title('Fare Distribution')
plt.show()

colors = ["pink","skyblue"]
plt.bar(survived_by_gender.index,survived_by_gender, color=colors)
plt.xlabel('Sex')
plt.ylabel('Survived')
plt.title('Survival by Sex')
plt.show()

survival_by_class = df.groupby("Pclass")["Survived"].mean() * 100
survival_by_class

colors = ["yellow","green","red"]
plt.bar(survival_by_class.index,survival_by_class, color=colors)
plt.xlabel('PClass')
plt.ylabel('Survived')
plt.title('Survival by PClass')
plt.show()

import matplotlib.pyplot as plt

plt.scatter(df["Age"], df["Fare"], c=df["Survived"], cmap="coolwarm", alpha=0.6)
plt.xlabel("Age")
plt.ylabel("Fare")
plt.title("Age vs Fare (colored by Survival)")
plt.colorbar(label="Survived (0=No, 1=Yes)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

age_not_survived = df[df['Survived'] == 0]['Age'].dropna()
age_survived = df[df['Survived'] == 1]['Age'].dropna()

plt.hist(
    age_not_survived,
    bins=20,
    alpha=0.6,
    label='Did Not Survive (0)',
    color='red'
)


plt.hist(
    age_survived,
    bins=20,
    alpha=0.6,
    label='Survived (1)',
    color='blue'
)

plt.title('Age Distribution Grouped by Survival Status')
plt.xlabel('Age (Years)')
plt.ylabel('Frequency (Number of Passengers)')
plt.legend()
plt.show()

summary = df.groupby(['Sex', 'Pclass'], observed=True).agg(
    Avg_Age=('Age', 'mean'),
    Avg_Fare=('Fare', 'mean'),
    Survival_Rate=('Survived', 'mean')
).reset_index()

summary['Survival_Rate'] = (summary['Survival_Rate'] * 100).map('{:.2f}%'.format)

print(summary.to_markdown())

data = {
    "Class": ["1st", "2nd", "3rd", "Crew"],
    "Passengers": [325, 285, 706, 885],
    "Survived": [201, 118, 178, 212],
    "Survival Rate": [61.8, 41.4, 25.2, 24.0]
}
summary = pd.DataFrame(data)

client = openai.OpenAI(api_key="INSERT YOUR API KEY")

system_context = f"""
You are an expert data analyst.
You are analyzing Titanic passenger statistics based on the following summary table:

{summary.to_markdown(index=False)}

Answer user questions about patterns, correlations, and insights in this data.
Always refer to specific numbers or relationships from the table when possible.
If the user asks for visualizations, describe how they could be created (e.g., bar chart, heatmap, etc.).
"""


user_question = input("Question:")

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "system", "content": system_context},
        {"role": "user", "content": user_question}
    ]
)

reply = response.choices[0].message.content
print(reply)